### ISSUE TITLE
Committing Realm transaction on networkQueue

### ISSUE THREAD

**Issue by khramtsoff** [allychat/android-sdk#2]
realm.executeTransaction должен вызываться на потоке, в котором был создан realm, иначе будет exception

**MessageController:105**

```
DispatchUtil.getInstance().networkQueue.postRunnable(new Runnable() {
    @Override
    public void run() {
        try {
            Response r = ServiceFactory.getChatApi().readMessage(messageId); //todo update status
            if (r.getStatus() == 200) {
                AllyChat.getInstance().getRealm().executeTransaction(new Realm.Transaction() {
```

**MessageController:147**

```
if (!roomExists) {
    DispatchUtil.getInstance().networkQueue.postRunnable(new Runnable() {
        @Override
        public void run() {
            final List<Room> rooms = ServiceFactory.getChatApi().getRooms();
            realm.executeTransaction(new Realm.Transaction() {
```

**MessageController:177**

```
DispatchUtil.getInstance().networkQueue.postRunnable(new Runnable() {
    @Override
    public void run() {
        if (message.getFile() != null)
            uploadImageAndUpdateMessage(message, fileUploadListener);

        try {
            final Message responseMessage = ServiceFactory.getChatApi().postMessage(message);
            Log.e("MSG", "successfully sent message, response: " + StringUtils.toString(responseMessage));
            AllyChat.getInstance().getRealm().executeTransaction(new Realm.Transaction() {
```

**Comment by tommototom** [comment]
Верно, только в методе `AllyChat.getInstance().getRealm()` не подставляется ссылка, а каждый раз достается realm для текущего треда. Поэтому exception будет возникать только во втором примере, где ссылка от `AllyChat.getInstance().getRealm()` передается в другой тред, но это исправлено в `1.3.18`.

**Comment by khramtsoff** [comment]
Отлично, спасибо

**AllyChatApi:121**

```
public static void readMessage(@NonNull final Message message, SimpleChatCallback<Void> callback)
```

Возможно нужна @NonNull на callback в этом месте и по цепочке дальше

**Comment by khramtsoff** [comment]
Еще мелочи (описки, ошибки компиляции) в Readme, думаю без них будет лучше :-) 
AllyChat.getInstance().close()
.build()
compile ('com.magneta.sdk:chat:1.3.+') { transitive = true }`
AllyChatApi.clearSession(true); // - метода нет

**Comment by tommototom** [comment]
AllyChat.getInstance().close()
.build()
а с этими что не так?
конечно лучше, никто не спорит, пофиксил

**Comment by khramtsoff** [comment]
Не хватает ";"

**Comment by tommototom** [comment]
теперь есть
